--TEST--
phpunit-skelgen --class -- BankAccountTest _fixture/BankAccountTest.php BankAccount php://stdout
--FILE--
<?php
$_SERVER['argv'][1] = '--class';
$_SERVER['argv'][2] = '--';
$_SERVER['argv'][3] = 'BankAccountTest';
$_SERVER['argv'][4] = __DIR__ . DIRECTORY_SEPARATOR . '_fixture' . DIRECTORY_SEPARATOR . 'BankAccountTest.php';
$_SERVER['argv'][5] = 'BankAccount';
$_SERVER['argv'][6] = 'php://stdout';

require __DIR__ . '/../src/autoload.php';
$textui = new SebastianBergmann\PHPUnit\SkeletonGenerator\Command;
$textui->main();
?>
--EXPECTF--
PHPUnit Skeleton Generator %s by Sebastian Bergmann.

<?php
/**
 * Generated by PHPUnit_SkeletonGenerator %s on %s at %s.
 */
class BankAccount
{
    /**
     * @todo Implement depositMoney().
     */
    public function depositMoney()
    {
        // Remove the following line when you implement this method.
        throw new RuntimeException('Not yet implemented.');
    }

    /**
     * @todo Implement getBalance().
     */
    public function getBalance()
    {
        // Remove the following line when you implement this method.
        throw new RuntimeException('Not yet implemented.');
    }

    /**
     * @todo Implement withdrawMoney().
     */
    public function withdrawMoney()
    {
        // Remove the following line when you implement this method.
        throw new RuntimeException('Not yet implemented.');
    }
}
Wrote skeleton for "BankAccount" to "php://stdout".
