--TEST--
phpunit-skelgen --test -- project\BankAccount _fixture/BankAccountNS.php BankAccountTest php://stdout
--FILE--
<?php
$_SERVER['argv'][1] = '--test';
$_SERVER['argv'][2] = '--';
$_SERVER['argv'][3] = 'project\\BankAccount';
$_SERVER['argv'][4] = __DIR__ . DIRECTORY_SEPARATOR . '_fixture' . DIRECTORY_SEPARATOR . 'BankAccountNS.php';
$_SERVER['argv'][5] = 'BankAccountTest';
$_SERVER['argv'][6] = 'php://stdout';

require __DIR__ . '/../src/autoload.php';
$textui = new SebastianBergmann\PHPUnit\SkeletonGenerator\Command;
$textui->main();
?>
--EXPECTF--
PHPUnit Skeleton Generator %s by Sebastian Bergmann.

<?php
/**
 * Generated by PHPUnit_SkeletonGenerator %s on %s at %s.
 */
class BankAccountTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var BankAccount
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BankAccount;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers project\BankAccount::getBalance
     * @todo   Implement testGetBalance().
     */
    public function testGetBalance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers project\BankAccount::depositMoney
     * @todo   Implement testDepositMoney().
     */
    public function testDepositMoney()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers project\BankAccount::withdrawMoney
     * @todo   Implement testWithdrawMoney().
     */
    public function testWithdrawMoney()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
Wrote skeleton for "BankAccountTest" to "php://stdout".
